### PR TITLE
Added styling and pages for section cards rendering

### PR DESCRIPTION
**Pull request by augustocollado**
Included in this PR:
- Styles for cards rendering
- Support for dark and light mode in card icons
- Added disclaimer

### CODE REVIEW

**Review by albertov19 — APPROVED** [review]
LGTM!

**Review by eshaben — CHANGES_REQUESTED** [review]
Just a lot of styles that were copied over but aren't relevant to the Tanssi docs site yet. Not sure what the status is on getting a home page designed, but I'd say that it is probably better to cross that bridge when you get there

If you have any questions, let me know!! 🙂

**Comment by augustocollado** [comment]
Deleted the unused copied styles, thanks!

**Review by eshaben — APPROVED** [review]
I pushed some css changes so that the disclaimer is rendered at the bottom of the page on index pages. There are a lot of moving parts, but just make sure that the pages that use the `index-page.html` and `subsection-index-page.html` template also have
```
hide:
 - toc
 - feedback
 ```

**Pull request merged**
